-- ============================================================================
-- MinWorkBuddy · 租户与租户管理员 初始化脚本 (PostgreSQL)
-- ----------------------------------------------------------------------------
-- 用途：
--   1) 定义 sys_tenant / sys_user / sys_role / sys_user_role / sys_tenant_package
--      等核心表的 DDL（已存在则跳过，不影响线上结构）。
--   2) 初始化 6 个业务租户，并为其各创建一个管理员账号。
--
-- 默认管理员密码统一为：admin123  （bcrypt 哈希已预生成，见下方 password_hash）
--   登录方式：用户名 = admin_finance 等；租户下拉选择对应租户后输入密码。
--
-- 幂等：可重复执行；依赖唯一约束（tenant_id / name / username / role_code）
--       与 NOT EXISTS 守卫，重复运行不会插入重复数据。
-- ============================================================================


-- ─────────────────────────────────────────────────────────────────────────
-- 1) DDL：相关表结构（CREATE TABLE IF NOT EXISTS，已存在则跳过）
--    说明：真实表结构由 alembic 迁移 001 维护，这里仅作为“初始化结构定义”
--          的参考/兜底；生产环境若已迁移则这些语句均为 no-op。
-- ─────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS sys_tenant_package (
    package_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'active',
    remark      VARCHAR(500),
    menu_ids    JSON,
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sys_tenant (
    tenant_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL UNIQUE,
    contact_name  VARCHAR(50),
    contact_mobile VARCHAR(20),
    status        VARCHAR(20)  NOT NULL DEFAULT 'active',
    package_id    BIGINT REFERENCES sys_tenant_package(package_id),
    expire_time   TIMESTAMP,
    account_count INTEGER       DEFAULT 0,
    websites      JSON,
    created_at    TIMESTAMP     NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP     NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sys_user (
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)   UNIQUE NOT NULL,
    password_hash VARCHAR(255)  NOT NULL,
    real_name     VARCHAR(100)  NOT NULL,
    phone         VARCHAR(20),
    email         VARCHAR(100),
    avatar_url    VARCHAR(500),
    status        VARCHAR(20)   NOT NULL DEFAULT 'active',
    is_admin      BOOLEAN        NOT NULL DEFAULT false,
    last_login_at TIMESTAMP,
    last_login_ip VARCHAR(50),
    created_at    TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP      NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMP,
    is_deleted    BOOLEAN        NOT NULL DEFAULT false,
    tenant_id     BIGINT
);
CREATE INDEX IF NOT EXISTS ix_sys_user_tenant_id ON sys_user(tenant_id);

CREATE TABLE IF NOT EXISTS sys_role (
    role_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name    VARCHAR(100) NOT NULL,
    role_code    VARCHAR(50)   UNIQUE NOT NULL,
    region_code  VARCHAR(20),
    region_level VARCHAR(20),
    description  TEXT,
    sort_order   INTEGER        DEFAULT 0,
    status       VARCHAR(20)    NOT NULL DEFAULT 'active',
    created_at   TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP      NOT NULL DEFAULT now(),
    is_deleted   BOOLEAN        NOT NULL DEFAULT false,
    tenant_id    BIGINT
);

CREATE TABLE IF NOT EXISTS sys_user_role (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES sys_user(user_id),
    role_id    BIGINT NOT NULL REFERENCES sys_role(role_id),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    tenant_id  BIGINT
);


-- ─────────────────────────────────────────────────────────────────────────
-- 2) 种子数据：6 个业务租户
--    （注：需求文案写“5 个”，但实际列出了 6 个名称，这里按列出的 6 个全部初始化）
-- ─────────────────────────────────────────────────────────────────────────

INSERT INTO sys_tenant (tenant_id, name, contact_name, contact_mobile, status, account_count)
VALUES
    (1, '金融投资', '金融投资管理員', '13800000001', 'active', 100),
    (2, '销售营销', '销售营销管理员', '13800000002', 'active', 100),
    (3, '法律AI',   '法律AI管理员',   '13800000003', 'active', 100),
    (4, '办公AI',   '办公AI管理员',   '13800000004', 'active', 100),
    (5, '教育AI',   '教育AI管理员',   '13800000005', 'active', 100),
    (6, '学习AI',   '学习AI管理员',   '13800000006', 'active', 100),
    (0, 'MiniWorkBuddy', '系统管理员', NULL, 'active', 9999)
ON CONFLICT DO NOTHING;


-- ─────────────────────────────────────────────────────────────────────────
-- 3) 种子数据：各租户的管理员用户
--    密码统一为 admin123，bcrypt 哈希：$2b$12$NgRUWcviQryzTh.W2Loryest7q9WNunRhFChbzWMkOaBAk8Wa03t2
-- ─────────────────────────────────────────────────────────────────────────

INSERT INTO sys_user (user_id, username, password_hash, real_name, status, is_admin, tenant_id, is_deleted)
VALUES
    (1001, 'admin_finance', '$2b$12$NgRUWcviQryzTh.W2Loryest7q9WNunRhFChbzWMkOaBAk8Wa03t2', '金融投资管理员', 'active', true, 1, false),
    (1002, 'admin_sales',   '$2b$12$NgRUWcviQryzTh.W2Loryest7q9WNunRhFChbzWMkOaBAk8Wa03t2', '销售营销管理员', 'active', true, 2, false),
    (1003, 'admin_legal',   '$2b$12$NgRUWcviQryzTh.W2Loryest7q9WNunRhFChbzWMkOaBAk8Wa03t2', '法律AI管理员',   'active', true, 3, false),
    (1004, 'admin_office',  '$2b$12$NgRUWcviQryzTh.W2Loryest7q9WNunRhFChbzWMkOaBAk8Wa03t2', '办公AI管理员',   'active', true, 4, false),
    (1005, 'admin_edu',     '$2b$12$NgRUWcviQryzTh.W2Loryest7q9WNunRhFChbzWMkOaBAk8Wa03t2', '教育AI管理员',   'active', true, 5, false),
    (1006, 'admin_study',   '$2b$12$NgRUWcviQryzTh.W2Loryest7q9WNunRhFChbzWMkOaBAk8Wa03t2', '学习AI管理员',   'active', true, 6, false),
    (9999, 'admin',          '$2b$12$NgRUWcviQryzTh.W2Loryest7q9WNunRhFChbzWMkOaBAk8Wa03t2', '超级管理员',     'active', true, 0, false)
ON CONFLICT (username) DO NOTHING;


-- ─────────────────────────────────────────────────────────────────────────
-- 4) 种子数据：各租户的“租户管理员”角色（role_code 全局唯一）
-- ─────────────────────────────────────────────────────────────────────────

INSERT INTO sys_role (role_id, role_name, role_code, status, tenant_id, is_deleted)
VALUES
    (1001, '租户管理员', 'tenant_admin_finance', 'active', 1, false),
    (1002, '租户管理员', 'tenant_admin_sales',   'active', 2, false),
    (1003, '租户管理员', 'tenant_admin_legal',   'active', 3, false),
    (1004, '租户管理员', 'tenant_admin_office',  'active', 4, false),
    (1005, '租户管理员', 'tenant_admin_edu',     'active', 5, false),
    (1006, '租户管理员', 'tenant_admin_study',   'active', 6, false),
    (9999, '超级管理员', 'super_admin',          'active', 0, false)
ON CONFLICT (role_code) DO NOTHING;


-- ─────────────────────────────────────────────────────────────────────────
-- 5) 绑定：管理员用户 ↔ 租户管理员角色（幂等守卫）
-- ─────────────────────────────────────────────────────────────────────────

INSERT INTO sys_user_role (user_id, role_id, tenant_id)
SELECT 1001, 1001, 1 WHERE NOT EXISTS (SELECT 1 FROM sys_user_role WHERE user_id = 1001 AND role_id = 1001);
INSERT INTO sys_user_role (user_id, role_id, tenant_id)
SELECT 1002, 1002, 2 WHERE NOT EXISTS (SELECT 1 FROM sys_user_role WHERE user_id = 1002 AND role_id = 1002);
INSERT INTO sys_user_role (user_id, role_id, tenant_id)
SELECT 1003, 1003, 3 WHERE NOT EXISTS (SELECT 1 FROM sys_user_role WHERE user_id = 1003 AND role_id = 1003);
INSERT INTO sys_user_role (user_id, role_id, tenant_id)
SELECT 1004, 1004, 4 WHERE NOT EXISTS (SELECT 1 FROM sys_user_role WHERE user_id = 1004 AND role_id = 1004);
INSERT INTO sys_user_role (user_id, role_id, tenant_id)
SELECT 1005, 1005, 5 WHERE NOT EXISTS (SELECT 1 FROM sys_user_role WHERE user_id = 1005 AND role_id = 1005);
INSERT INTO sys_user_role (user_id, role_id, tenant_id)
SELECT 1006, 1006, 6 WHERE NOT EXISTS (SELECT 1 FROM sys_user_role WHERE user_id = 1006 AND role_id = 1006);

-- 超级管理员 admin ↔ super_admin 角色（tenant_id = 0）
INSERT INTO sys_user_role (user_id, role_id, tenant_id)
SELECT 9999, 9999, 0 WHERE NOT EXISTS (SELECT 1 FROM sys_user_role WHERE user_id = 9999 AND role_id = 9999);


-- ─────────────────────────────────────────────────────────────────────────
-- 6) 重置自增序列，避免后续 INSERT 与显式 ID 冲突
-- ─────────────────────────────────────────────────────────────────────────

SELECT setval(pg_get_serial_sequence('sys_tenant', 'tenant_id'), COALESCE((SELECT MAX(tenant_id) FROM sys_tenant), 1), true);
SELECT setval(pg_get_serial_sequence('sys_user',   'user_id'),   COALESCE((SELECT MAX(user_id)   FROM sys_user),   1), true);
SELECT setval(pg_get_serial_sequence('sys_role',   'role_id'),   COALESCE((SELECT MAX(role_id)   FROM sys_role),   1), true);
SELECT setval(pg_get_serial_sequence('sys_user_role', 'id'),      COALESCE((SELECT MAX(id)        FROM sys_user_role), 1), true);
